### PR TITLE
Add workflow to auto-deploy images

### PR DESCRIPTION
**Pull request by ipince**
Build and deploy images to `github-public` upon merges.

Also adds devbox.json to make things easier (build from devbox).

Tested:
https://console.cloud.google.com/artifacts/docker/dev-j3tpk/us-east4/github-public/go-gin

### CODE REVIEW

**Comment by loreto** [comment]
So ... two questions:
1. I'm not sure the github action should live in this repo. If it does, it is part of the template, right? Which means that when we clone the environment and you end up with a project, that project is gonna contain this CICD github flow that is specific to us.

2. Are you thinking you are gonna have to create the same flow over and over for each of the examples?

**Review by LucilleH — APPROVED** [review]
Do we have to add this for every single template repo?

**Review by loreto — CHANGES_REQUESTED** [review]
> Do we have to add this for every single template repo?

I'm still not sure we should check this in: because it'll become part of the template

**Comment by ipince** [comment]
> I'm not sure the github action should live in this repo. If it does, it is part of the template, right? Which means that when we clone the environment and you end up with a project, that project is gonna contain this CICD github flow that is specific to us.

Well, if you clone the repo, then yeah, I'd guess you'd end up with this action in the repo, good point. I will not work, of course, but yes, it'll be there. We could have the action perform a no-op and succeed if the repo is not this one, so at least it doesn't fail when you clone it.

Other than that... any other suggestions? In which other way could we keep the template images fresh? Remember to push manually?

> Are you thinking you are gonna have to create the same flow over and over for each of the examples?

Yes. This is just an example. The next step would be to put the generalized action in its own repo, and then just run it from all the others.

**Comment by ipince** [comment]
> Do we have to add this for every single template repo?

Yes, but we can just call the action if it lives in its own repo.

**Comment by loreto** [comment]
> > I'm not sure the github action should live in this repo. If it does, it is part of the template, right? Which means that when we clone the environment and you end up with a project, that project is gonna contain this CICD github flow that is specific to us.
> 
> Well, if you clone the repo, then yeah, I'd guess you'd end up with this action in the repo, good point. I will not work, of course, but yes, it'll be there. We could have the action perform a no-op and succeed if the repo is not this one, so at least it doesn't fail when you clone it.
> 
> Other than that... any other suggestions? In which other way could we keep the template images fresh? Remember to push manually?
> 
> > Are you thinking you are gonna have to create the same flow over and over for each of the examples?
> 
> Yes. This is just an example. The next step would be to put the generalized action in its own repo, and then just run it from all the others.

I think you, me, Josh should sync up so that everything works well together. As is, Josh's work will fork the repo with all files in it, which means that if someone starts the project from the template, they'll end up with a repo in their own account with these github actions (which will run, but fail, and show a broken build!)

Options I see:
1. We change the template cloning logic to purposefully ignore github actions
2. We create a CICD pipeline outside of these repos that checks them out, builds the image, then pushes them.
3. We move the examples to axiom, have the CICD pipeline there, and we publish from axiom to `jetify-examples` just like we publish to `opensource`

Open to other ideas as well!

**Comment by ipince** [comment]
Closing in favor of publishing code and images from the opensource repo, as discussed.

**Pull request closed without merging**
